#!/usr/bin/env bash
#
# dev.sh — one-stop setup + task runner for the spammer mocks.
#
# First time:   ./dev.sh setup      (venv + deps + Postgres + .env)
# Then:         ./dev.sh test
#               ./dev.sh prepare
#               ./dev.sh serve
#               ./dev.sh status | inject ... | emit ... | reset --confirm=yes
#               ./dev.sh token
#
# Everything (venv path, DB connection string) is handled for you and cached in
# .env — you never need to `export` anything.
set -euo pipefail
cd "$(dirname "$0")"

VENV=.venv
PY="$VENV/bin/python"
SPAMMER="$VENV/bin/spammer"
ENV_FILE=.env

# Defaults for `prepare` (override inline, e.g. SEED=7 ./dev.sh prepare).
SIZE="${SIZE:-small}"
RUNTIME="${RUNTIME:-few_months}"
SEED="${SEED:-42}"
PORT="${PORT:-7001}"

# Candidate DB credentials, tried in order during setup.
# Set SPAMMERS_DB_CREDS=user:pass to use your own.
CRED_CANDIDATES=("${SPAMMERS_DB_CREDS:-}" "postgres:postgres" "company_os:company_os")

c_green() { printf '\033[32m%s\033[0m\n' "$1"; }
c_red()   { printf '\033[31m%s\033[0m\n' "$1" >&2; }

load_env() {
    if [ -f "$ENV_FILE" ]; then set -a; . "$ENV_FILE"; set +a; fi
}

require_setup() {
    if [ ! -x "$PY" ] || [ ! -f "$ENV_FILE" ]; then
        c_red "Not set up yet. Run: ./dev.sh setup"
        exit 1
    fi
}

pg_reachable() { (exec 3<>/dev/tcp/localhost/5432) 2>/dev/null; }

ensure_postgres() {
    if pg_reachable; then return; fi
    echo "Postgres not listening on localhost:5432 — trying to start a Docker container..."
    if command -v docker >/dev/null 2>&1; then
        local cid
        cid="$(docker ps -aq --filter 'publish=5432' | head -1 || true)"
        if [ -n "$cid" ]; then
            docker start "$cid" >/dev/null
            for _ in 1 2 3 4 5 6 7 8 9 10; do pg_reachable && break; sleep 1; done
        fi
    fi
    pg_reachable || { c_red "Could not reach Postgres on localhost:5432. Start it and re-run ./dev.sh setup"; exit 1; }
}

# Print the first credential pair that can open a maintenance connection.
detect_creds() {
    local cred
    for cred in "${CRED_CANDIDATES[@]}"; do
        [ -z "$cred" ] && continue
        if "$PY" - "postgresql://${cred}@localhost:5432/postgres" >/dev/null 2>&1 <<'PY'
import asyncio, asyncpg, sys
async def main():
    c = await asyncpg.connect(sys.argv[1])
    await c.close()
asyncio.run(main())
PY
        then echo "$cred"; return 0; fi
    done
    return 1
}

cmd_setup() {
    echo "==> Python venv + dependencies"
    [ -d "$VENV" ] || python3 -m venv "$VENV"
    "$VENV/bin/pip" install -q --upgrade pip
    "$VENV/bin/pip" install -q -e ".[dev]"

    echo "==> Postgres"
    ensure_postgres
    local cred
    if ! cred="$(detect_creds)"; then
        c_red "No working Postgres credentials. Tried: ${CRED_CANDIDATES[*]}"
        c_red "Set one explicitly: SPAMMERS_DB_CREDS=user:pass ./dev.sh setup"
        exit 1
    fi
    echo "    using credentials: ${cred%%:*}:****"

    echo "==> Writing $ENV_FILE"
    cat > "$ENV_FILE" <<EOF
# Auto-generated by ./dev.sh setup — edit the credentials here if they change.
SPAMMERS_DB_URL=postgresql://${cred}@localhost:5432/mock_orgs
SPAMMERS_TEST_DB_URL=postgresql://${cred}@localhost:5432/spammers_test
EOF

    echo "==> Creating + migrating the mock_orgs database"
    load_env
    "$PY" - <<'PY'
import asyncio
from spammers.common.db import ensure_database_exists, create_pool, apply_migrations
async def main():
    await ensure_database_exists()
    pool = await create_pool()
    applied = await apply_migrations(pool)
    await pool.close()
    print("    migrations:", ", ".join(applied) or "(none)")
asyncio.run(main())
PY
    c_green "Setup complete. Try: ./dev.sh test   or   ./dev.sh prepare && ./dev.sh serve"
}

cmd_test() {
    require_setup; load_env
    # With no path args, pytest uses `testpaths` (spammers/tests) from pyproject.
    exec "$PY" -m pytest "$@"
}

cmd_prepare() {
    require_setup; load_env
    local tid; tid="$("$PY" -c 'import uuid; print(uuid.uuid4())')"
    echo "Preparing run (size=$SIZE runtime=$RUNTIME seed=$SEED, tenant=$tid)..."
    "$SPAMMER" prepare \
        --size="$SIZE" --runtime="$RUNTIME" --seed="$SEED" \
        --tenant-id="$tid" --fyralis-base=http://localhost:8000 "$@"
}

cmd_serve() {
    require_setup; load_env
    local provider="${1:-slack}"
    local default_port
    case "$provider" in
        slack)    default_port=7001 ;;
        discord)  default_port=7002 ;;
        github)   default_port=7003 ;;
        gmail)    default_port=7004 ;;
        calendar) default_port=7005 ;;
        notion)   default_port=7006 ;;
        *) c_red "unknown provider: $provider (use slack|discord|github|gmail|calendar|notion)"; exit 1 ;;
    esac
    local port="${PORT:-$default_port}"
    echo "$provider mock on http://localhost:$port  (health: /_health)"
    exec "$PY" -m "spammers.$provider" run --port "$port"
}

cmd_studio() {
    require_setup; load_env
    local port="${PORT:-7000}"
    echo "Spammer Studio on http://localhost:$port  (control + observe the mocks)"
    exec "$PY" -m spammers.studio --port "$port"
}

cmd_stop() {
    local port="${PORT:-7001}"
    if command -v fuser >/dev/null 2>&1 && fuser -k "${port}/tcp" 2>/dev/null; then
        sleep 1
        c_green "Stopped the mock listening on port $port"
    else
        echo "Nothing listening on port $port"
    fi
}

cmd_token() {
    require_setup; load_env
    "$PY" - <<'PY'
import asyncio
from spammers.common.db import create_pool
async def main():
    pool = await create_pool()
    row = await pool.fetchrow("SELECT bot_token FROM app_slack.workspaces ORDER BY ctid DESC LIMIT 1")
    print(row["bot_token"] if row else "no workspace yet — run ./dev.sh prepare first")
    await pool.close()
asyncio.run(main())
PY
}

usage() {
    cat <<EOF
dev.sh — setup + task runner for the spammer mocks

  ./dev.sh setup              Build everything (venv, deps, Postgres, .env). Run once.
  ./dev.sh test [pytest args] Run the Slack fidelity suite
  ./dev.sh prepare            Seed a synthetic org + historical timeline
  ./dev.sh serve [slack|discord|github|gmail|calendar|notion]
                              Start a mock (slack:7001 discord:7002 github:7003
                              gmail:7004 calendar:7005 notion:7006; \$PORT overrides)
  ./dev.sh studio             Launch the Studio control UI (http://localhost:7000)
  ./dev.sh stop               Stop the mock (frees port \$PORT, default 7001)
  ./dev.sh token              Print a bot token for curl-ing the mock
  ./dev.sh status             Show run + clock + counts
  ./dev.sh inject --text=… --channel=#general
  ./dev.sh emit --speed=1.0 --live-rate=10
  ./dev.sh reset --confirm=yes
  ./dev.sh install --provider=slack ...

Overrides: SIZE, RUNTIME, SEED, PORT, SPAMMERS_DB_CREDS (e.g. SEED=7 ./dev.sh prepare)
EOF
}

cmd="${1:-help}"; shift || true
case "$cmd" in
    setup)   cmd_setup "$@" ;;
    test)    cmd_test "$@" ;;
    prepare) cmd_prepare "$@" ;;
    serve)   cmd_serve "$@" ;;
    studio)  cmd_studio "$@" ;;
    stop)    cmd_stop ;;
    token)   cmd_token ;;
    status|inject|emit|jump|reset|install)
             require_setup; load_env; exec "$SPAMMER" "$cmd" "$@" ;;
    help|-h|--help) usage ;;
    *) c_red "Unknown command: $cmd"; echo; usage; exit 1 ;;
esac
